#!/system/bin/bash
C1="\e[31;1m"
C2="\e[32;1m"
C3="\e[33;1m"
C4="\e[34;1m"
C5="\e[35;1m"
C6="\e[36;1m"
CD="\e[0m"
dalvik(){
cout "[ CLEARING DALVIK CACHE ]"
cout "[ IT NEEDS ABOVE 5 MINUTES FOR NEXT RESTART, PLEASE BE PATIENT ]"
rm -rf /data/dalvik-cache/*
sleep 3
cout "[ HeHe Boi ]" &
alsa_aplay /system/etc/sounds/done.sos > /dev/null 2>&1
sec=3
while [ $sec -ge 0 ]; do
echo -ne "\e[33;1mRebooting in:-\e[91;1m $sec \e[0m\033[0K\r"
let "sec=sec-1"
sleep 1
done
reboot    
}
cache(){
cout "[ CLEARING APP CACHE ]"
cd /data/data
find . -name cache -type d -exec rm -rf {} +
cd /data/media/0/Android/data
find . -name cache -type d -exec rm -rf {} +
sleep 3
cout "[ HeHe Boi ]" &
alsa_aplay /system/etc/sounds/done.sos > /dev/null 2>&1
cout "[ Press ALT+F7 or ALT+FN+F7 to Exit ]"
}
cli(){
center "Welcome"
logo "Clear-Cache/Dalvik"
center "Heheboi" 
echo 
cout "[ MADE BY SPECTRE ]"
cout "[ THIS SCRIPT IS USED TO CLEAR CACHE  ]"
cout "[ CAUTION: DONT USE THIS SCRIPT UNNECESSARILY , USE ONLY WHEN YOUR SYSTEM BECAME EXTREMELY LAGGY ]"
cout "[ Select the options below ]"
cout "1] CLEAR DALVIK CACHE."
cout "2] CLEAR APP CACHE."
cout "3] Return To Main Menu."
cout "4] Exir."
echo -e "\e[93;1m"
read -p "Enter The Option:- " c 
echo -e "\e[0m"
clear
case $c in
1)
dalvik
;;
2)
cache
;;
3)
bash /system/script/menu
;;
4)
exit 
;;
*)
cout "Ah Boi Here We Go Again....!"
sleep 1
clear 
cli 
;;
esac    
}
clear
cli