#!/system/bin/bash
C1="\e[31;1m"
C2="\e[32;1m"
C3="\e[33;1m"
C4="\e[34;1m"
C5="\e[35;1m"
C6="\e[36;1m"
CD="\e[0m"
init(){
mv -f /data/media/0/spectre/init.sh /system/etc/
cd /system/etc
chmod 755 init.sh
cout  "${C3}[ HeHe Boi ]${CD}${CN}"
alsa_aplay /system/etc/sounds/done.sos > /dev/null 2>&1
cout  "${C3}[ REBOOTING ]${CD}${CN}"
reboot
}
cli(){
center "Welcome"
logo "Init-Fixer"
center "Heheboi"
echo 
cout "${C3}[ SCRIPT MADE BY SPECTRE ]${CD}${CN}"
cout "${C3}[ THIS SCRIPT IS USED TO LOAD ALSA PROFILE, LOAD WIFI MODULE (IF EXIST IN KERNEL) ETC. ]${CD}${CN}"
cout "${C3}[ CAUTION: DON'T USE init.sh FILE FROM OTHER SOURCE, ASK Ghost TEAM ]${CD}${CN}"
cout "${C3}[ COPY init.sh FILE TO spectre FOLDER ]${CD}${CN}"
cout "${C2} [1] Init_fix.${CD}${CN}"
cout "${C4} [2] Return To Main-menu.${CD}${CN}"
cout "${C1} [3] Exit.${CD}${CN}"
echo -e "\e[93;1m"
read -p "Enter The option:- " c 
echo -e "\e[0m"
clear
case $c in
1)
init
;;
2)
bash /system/script/menu
;;
3)
exit 
;;
*)
cout "${C3}Ah Boi Here We Go Again....${CD}${CN}"
sleep 1
clear 
cli 
;;
esac    
}
clear
cli
