#!/system/bin/bash
center "Welcome"
logo "Google-Service"
center "Heheboi"
echo 
cout "\e[93;1m Googel Service.\e[0m"
cout "\e[92;1m1]Disbale All Google Service.\e[0m"
cout "\e[94;1m2]Disable GoogleApp Expect(playstore)\e[0m"
cout "\e[92;1m3]Enable All Service.\e[0m"
cout "\e[96;1m4]Enable Youtube And Chorme.\e[0m"
cout "\e[94;1m5]Return To Main menu.\e[0m"
cout "\e[91;1m6]Exit.\e[0m"
echo -e "\e[93;1m"
read -p "Choose You Option Here >" c 
echo -e "\e[0m"
clear
case $c in 
1)
cout "\e[93;1mAll google Will disabled Now....!\e[0m"
mv /system/app/YouTube/YouTube.apk /system/app/YouTube/YouTube.lol > /dev/null 2>&1 
pm disable com.android.chrome > /dev/null 2>&1
pm disable com.android.vending > /dev/null 2>&1
mv /system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk /system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.lol > /dev/null 2>&1
alsa_aplay /system/etc/sounds/done.sos > /dev/null 2>&1
echo 
cout "\e[92;1mHeheboi..!\e[0m"
echo 
sleep 2
sec=5
while [ $sec -ge 0 ]; do
echo -ne "\e[33;1mRebooting in:-\e[91;1m $sec \e[0m\033[0K\r"
let "sec=sec-1"
sleep 1
done
reboot ;; 
2)
cout "\e[92;1mDisable GoogleApp Expect(playstore)\e[0m"
mv /system/app/YouTube/YouTube.apk /system/app/YouTube/YouTube.lol > /dev/null 2>&1   
pm disable com.android.chrome > /dev/null 2>&1
alsa_aplay /system/etc/sounds/done.sos > /dev/null 2>&1
echo
cout "\e[92;1mHeheboi..!\e[0m"
echo
sleep 2
sec=5
while [ $sec -ge 0 ]; do
echo -ne "\e[33;1mRebooting in:-\e[91;1m $sec \e[0m\033[0K\r"
let "sec=sec-1"
sleep 1
done
reboot ;;
3)
cout "\e[93;1mEnable All Service.\e[0m"
mv /system/app/YouTube/YouTube.lol /system/app/YouTube/YouTube.apk > /dev/null 2>&1  
pm enable com.android.chrome > /dev/null 2>&1
pm enable com.android.vending > /dev/null 2>&1
mv /system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.lol /system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk > /dev/null 2>&1
alsa_aplay /system/etc/sounds/done.sos > /dev/null 2>&1
echo
cout "\e[92;1mHeheboi..!\e[0m"
echo
sleep 2
sec=5
while [ $sec -ge 0 ]; do
echo -ne "\e[33;1mRebooting in:-\e[91;1m $sec \e[0m\033[0K\r"
let "sec=sec-1"
sleep 1
done
reboot ;; 
4)
cout "\e[96;1mEnable Youtube And Chorme.\e[0m"
mv /system/app/YouTube/YouTube.lol /system/app/YouTube/YouTube.apk > /dev/null 2>&1  
pm enable com.android.chrome > /dev/null 2>&1
alsa_aplay /system/etc/sounds/done.sos > /dev/null 2>&1
echo
cout "\e[92;1mHeheboi..!\e[0m"
echo 
sleep 2
sec=5
while [ $sec -ge 0 ]; do
echo -ne "\e[33;1mRebooting in:-\e[91;1m $sec \e[0m\033[0K\r"
let "sec=sec-1"
sleep 1
done
reboot ;;
5)
bash /system/script/menu ;;
6)
exit ;;
esac 