#!/system/bin/bash
#funcations for img2folder 
C1="\e[31;1m"
C2="\e[32;1m"
C3="\e[33;1m"
C4="\e[34;1m"
C5="\e[35;1m"
C6="\e[36;1m"
CD="\e[0m"
img2folder(){
if mount | grep "system" | grep "type ext"; then
y=$(find /GhostRoot -maxdepth 4 -type f -name heheboi.nab)
z=${y%/*}
F=$z/system.img
if [ -f "$F" ]; then
cout "[ System.img is being converted To System Folder... ]"
echo -e "${C6}          Progress   ${C5}   Speed     ${C3}   Time${CD}${CN}"
rsync -ah --info=progress2 /system $z  
sleep 1
cout " "
cout "[ Removing system.img ]"
rm -r $z/system.img 
cout "[ Finishing up... ]"
sync
sleep 0.6
cout "Heheboi....!" &
alsa_aplay /system/etc/sounds/done.sos > /dev/null 2>&1
sec=5
while [ $sec -ge 0 ]; do
echo -ne "\e[33;1mRebooting in:-\e[91;1m $sec \e[0m\033[0K\r"
let "sec=sec-1"
sleep 1
done
reboot
else
cout "[ System folder already Exists ]"
cout "[ Press Alt + f7  To close Terminal...]"
fi
else 
cout "Cant Be Img2Folder Because your in Ntfs Partition.!"
fi
}
folder2ext4(){
y=$(find /GhostRoot -maxdepth 4 -type f -name heheboi.nab)
z=${y%/*}  
cout "Checking Img2Folder form....!"
F=$z/system 
if [ -d "$F" ]; then
cout "System_Folder Found....!"
cout "Converting To image....!"
mkdir -m777 /sdcard/imgm
mkdir /sdcard/img
sleep 1
cout "Creating Empty Image file....!"
dd if=/dev/zero of=/sdcard/img/system.img bs=1M count=4096 > /dev/null 2>&1
echo 
cout "Ext4_System.img Done...!"
sleep 1
clear 
cout "Moving System_Folder in image....(Press y To Start Process....)."
cout " "
mke2fs -t ext4  /sdcard/img/system.img 
echo
sleep 0.5
mount -o loop /sdcard/img/system.img /sdcard/imgm
sleep 0.5
clear
echo -e "${C6}          Progress   ${C5}   Speed     ${C3}   Time${CD}${CN}"
rsync -ah --info=progress2 /system/* /sdcard/imgm 
umount /sdcard/imgm
cout ""
cout "Heheboi..!" &
alsa_aplay /system/etc/sounds/done.sos > /dev/null 2>&1
cout "Moving system.img In Ext4_Partition."
mv /sdcard/img/system.img $z 
cout "Successfully Moved to ext4_partition..!"
rmdir /sdcard/img
rmdir /sdcard/imgm 
cout "Boot Linux/Windows And Go To Ext4_partition Delete System_Folder."
sleep 2
sec=5
while [ $sec -ge 0 ]; do
echo -ne "\e[33;1mRebooting in:-\e[91;1m $sec \e[0m\033[0K\r"
let "sec=sec-1"
sleep 1
done
reboot
else
cout "System.img already Thier In Ext4 Partition." 
fi
}
#CLI
cli(){
clear 
center "Welcome"
logo "Img2Folder" 
center "Heheboi"
cout "Made By Narendra From GhostX Official."   
cout "Img2Folder /${C5}Ext4_to_Img.${CD}${CN}"
cout "Please Select Your option Here."
cout "1] Img2Folder."
cout "2] Folder2Img."
cout "3] Return TO Main_Menu."
cout "4] Exit."
echo -e "\e[93;1m"
read -p "Enter the Option:- " c 
echo -e "\e[0m"
clear
case $c in 
1)
img2folder
;;
2)
folder2ext4
;;
3)
bash /system/script/menu 
;;
4)
exit 2
;;
*)
clear
cout "AHH Boi Here We Go Again.....!"
sleep 1
cli 
;;
esac
}
# Funaction start here
cli 
