#!/system/bin/bash
#funcations for img2folder 
C1="\e[31;1m"
C2="\e[32;1m"
C3="\e[33;1m"
C4="\e[34;1m"
C5="\e[35;1m"
C6="\e[36;1m"
CD="\e[0m"
img2folder(){
if grep "system" | grep "type ext"; then
y=$(find /GhostRoot -maxdepth 4 -type f -name heheboi.nab)
z=${y%/*}
F=$z/system.img
if [ -f "$F" ]; then
cout "${C3}[ System.img is being converted To System Folder... ]${CD}${CN}"
echo -e "${C6}          Progress   ${C5}   Speed     ${C3}   Time${CD}${CN}"
rsync -ah --info=progress2 /system $z  
sleep 1
cout " "
cout "${C3}[ Removing system.img ]${CD}${CN}"
rm -r $z/system.img 
cout "${C5}[ Finishing up... ]${CD}${CN}"
sync
sleep 0.6
cout "${C3}[ Heheboi........]${CD}${CN}"
alsa_aplay /system/etc/sounds/done.sos > /dev/null 2>&1
sec=5
while [ $sec -ge 0 ]; do
echo -ne "\e[33;1mRebooting in:-\e[91;1m $sec \e[0m\033[0K\r"
let "sec=sec-1"
sleep 1
done
reboot
else
cout "${C4}[ System folder already Exists... ]${CD}${CN}"
cout "${C3}[ Press Alt + f7  To close Terminal...]${CD}${CN}"
fi
else 
cout "Cant Be Img2Folder Because your in Ntfs Partition.!"
fi
}
folder2ext4(){
y=$(find /GhostRoot -maxdepth 4 -type f -name heheboi.nab)
z=${y%/*}  
cout "${C2}Checking ${C6}Img2Folder${CD}${C3}form....${CD}${CN}"
F=$z/system 
if [ -d "$F" ]; then
cout "${C2} System_Folder Found....${CD}${CN}"
cout "${C3} Converting To image....${CD}${CN}"
mkdir -m777 /sdcard/imgm
mkdir /sdcard/img
sleep 1
cout "${C4}Creating Empty Image file....${CD}${CN}"
dd if=/dev/zero of=/sdcard/img/system.img bs=1M count=4096 > /dev/null 2>&1
echo 
cout "${C3}Ext4_System.img Done..${CD}${CN}"
sleep 1
clear 
cout "${C5}Moving System_Folder in image....(Press y To Start Process....)${CD}${CN}"
cout " "
mke2fs -t ext4  /sdcard/img/system.img 
echo
sleep 0.5
mount -o loop /sdcard/img/system.img /sdcard/imgm
sleep 0.5
clear
echo -e "${C6}          Progress   ${C5}   Speed     ${C3}   Time${CD}${CN}"
rsync -ah --info=progress2 /system/* /sdcard/imgm 
umount /sdcard/imgm
cout ""
cout "${C3}Heheboi${CD}${CN}"
alsa_aplay /system/etc/sounds/done.sos > /dev/null 2>&1
cout "${C4}Moving system.img In Ext4_Partition.${CD}${CN}"
mv /sdcard/img/system.img $z 
cout "${C3}Moved.${CD}${CN}"
rmdir /sdcard/img
rmdir /sdcard/imgm 
cout "${C6}Boot Linux/Windows And Go To Ext4_partition Delete ${C1}System_Folder${CD}.${CD}${CN}"
sleep 2
sec=5
while [ $sec -ge 0 ]; do
echo -ne "\e[33;1mRebooting in:-\e[91;1m $sec \e[0m\033[0K\r"
let "sec=sec-1"
sleep 1
done
reboot
else
cout "${C1}System.img already Thier In Ext4 Partition.${CD}${CN}" 
fi
}
#CLI
cli(){
clear 
center "Welcome"
logo "Img2Folder" 
center "Heheboi"
cout "${C6}Made By Narendra From GhostX Official.${CD}${CN}"   
cout "${C3}Img2Folder${CD}/${C5}Ext4_to_Img${CD}${CN}"
cout "${C3}Please Select Your option Here${CD}${CN}"
cout "${C2} [1] Img2Folder.${CD}${CN}"
cout "${C3} [2] Folder2Img.${CD}${CN}"
cout "${C4} [3] Return TO Main_Menu.${CD}${CN}"
cout "${C1} [4] Exit.${CD}${CN}"
echo -e "\e[93;1m"
read -p "Enter the Option:- " c 
echo -e "\e[0m"
clear
case $c in 
1)
img2folder
;;
2)
folder2ext4
;;
3)
bash /system/script/menu 
;;
4)
exit 2
;;
*)
clear
cout "${C3}AHH Boi Here We Go Again.....${CD}${CN}"
sleep 1
cli 
;;
esac
}
# Funaction start here
cli 
