#!/system/bin/bash
clear
menu(){
center "Welcome To Sos"
logo "Main-Menu"
center "Heheboi"
echo 
cout "                                                             \e[94;1;3;107m[ Main Menu Of (sos) ]\e[0m"
sleep 0.1
cout "                                                              \e[93;1m [1] Extreme Mode. \e[0m"
sleep 0.1
cout "                                                              \e[92;1m [2] Game-Center. \e[0m"
sleep 0.1
cout "                                                              \e[94;1m [3] Img2Folder/Folder2Img.\e[0m"
sleep 0.1
cout "                                                              \e[92;1m [4] Miscellaneous functions.\e[0m"
sleep 0.1
cout "                                                              \e[92;1m [5] Performance Tweaks.\e[0m"
sleep 0.1
cout "                                                              \e[92;1m [6] System Tweaks.\e[0m"
sleep 0.1
cout "                                                              \e[93;1m [7] Update Kernel.\e[0m"
sleep 0.1
cout "                                                              \e[94;1m [8] Update Mesa. \e[0m"
sleep 0.1
cout "                                                              \e[93;1m [9] Auto-Timer PowerOff.\e[0m"
sleep 0.1
cout "                                                              \e[91;1m [e] Exit from sos. \e[0m"
sleep 0.1
echo -e "                                                                 \e[91;1m[a]About_MOD\e[0m\e[0m"  
echo -e "\e[93;1m"
read -p "Enter your Option :- " c 
echo -e "\e[0m"
clear 
case $c in 
1)
bash /system/script/extreme
;;
2)
clear
game(){
center "Welcome"
logo "Game-Center"
center "Heheboi"
echo 
cout "\e[92;1m[1] PUBGM ( BACKUP & RESTORE)\e[0m" 
cout "\e[93;1m[2] PUBG Refresher.\e[0m" 
cout "\e[94;1m[3] Ghost Recoder(video only).\e[0m"
cout "\e[96;1m[4] Keymapper ( Backup & Restore).\e[0m" 
cout "\e[95;1m[5] Return To Main Menu.\e[0m" 
cout "\e[91;1m[6] Exit.\e[0m" 
echo -e "\e[93;1m"
read -p "Enter The Option:- " c 
echo -e "\e[0m"
clear 
case $c in 
1)
bash /system/script/game/pubg
;;
2)
bash /system/script/game/pubgrefresher 
;;
3)
bash /system/script/game/recoder 
;;
4)
bash /system/script/game/key ;;
5)
bash /system/script/menu ;; 
6)
exit 
;;
*)
cout "\e[93;1mAH Boi Here We Go Again.\e[0m"
sleep 0.7
clear 
game
;;
esac 
}
game
;;
3)
bash /system/script/img 
;;
4)
misc(){
center "Welcome"
logo "Miscellaneous"
center "Heheboi"
echo 
cout "\e[92;1m[1]Partition Mounter.\e[0m"
cout "\e[93;1m[2]Data Re-size.\e[0m" 
cout "\e[95;1m[3]System Re-size.\e[0m" 
cout "\e[92;1m[4]Google Service.\e[0m"
cout "\e[94;1m[5]Tablet Mode Or Desktop Mode. \e[0m" 
cout "\e[93;1m[6]Return To Main menu.\e[0m"
cout "\e[91;1m[7]Exit.\e[0m"
echo -e "\e[93;1m"
read -p "Enter The Option:- " c 
echo -e "\e[0m"
clear
case $c in 
1)
bash /system/script/misc/part 
;;
2)
bash /system/script/misc/data ;;
3)
bash /system/script/misc/system ;;
4)
bash /system/script/misc/google ;;
5)
bash /system/script/misc/cz ;; 
6)
bash /system/script/menu 
;;
7)
exit 
;;
*)
cout "\e[93;1mAh Boi Here We Go Again.\e[0m"
sleep 0.7
clear 
misc
;;
esac 
}
misc
;;
5)
bash /system/script/Performance ;;
6)
system_tweaks(){
center "Welcome"
logo "System-Tweaks"
center "Heheboi"
echo 
cout "\e[94;1m[1]Animations.\e[0m" 
cout "\e[95;1m[2]Cache.\e[0m"
cout "\e[96;1m[3]Firmware.\e[0m" 
cout "\e[93;1m[4]Init-Fix.\e[0m"
cout "\e[92;1m[5]Resolution.\e[0m"
cout "\e[93;1m[6]Return Main Menu.\e[0m"
cout "\e[91;1m[e]Exit.\e[0m"
echo 
echo -e "\e[93;1m"
read -p "Enter The Option Here:- " c 
echo -e "\e[0m"   
clear 
case $c in 
1)
bash /system/script/systemtweaks/ani 
;;
2)
bash /system/script/systemtweaks/cache 
;;
3)
bash /system/script/systemtweaks/firmware
;;
4)
bash /system/script/systemtweaks/init 
;;
5)
bash /system/script/systemtweaks/resolution
;;
6)
clear 
bash /system/script/menu
;;
e)
exit 
;;
*)
cout "\e[93;1mAh Boi Here We go Again....\e[0m"
sleep 0.7
clear 
system_tweaks
;;
esac
}
system_tweaks
;;
7)
bash /system/script/kernel 
;;
8)
bash /system/script/mesa 
;;
9)
bash /system/script/poweroff
;;
e)
exit 
;;
a)
bash /system/script/about
;;
s)
bash /system/script/status
;;
b) 
if [ -f /system/etc/sounds/sos.bak ]; then 
st=$(echo on )
else
st=$(echo off)
fi
if [ -f /system/etc/sounds/sos.sos ]; then 
mv /system/etc/sounds/sos.sos /system/etc/sounds/sos.bak > /dev/null 2>&1
mv /system/etc/sounds/done.sos /system/etc/sounds/done.bak > /dev/null 2>&1
cout "\e[93;1m Sound Off..!\e[0m"
sleep 1
menu 
else 
mv /system/etc/sounds/sos.bak /system/etc/sounds/sos.sos > /dev/null 2>&1  
mv /system/etc/sounds/done.bak /system/etc/sounds/done.sos > /dev/null 2>&1
cout "\e[93;1m Sound On..!\e[0m"
sleep 1
menu 
fi
;;
*)
cout "\e[93;1mAh Boi Here We Go Again..\e[0m"
sleep 1
clear 
menu 
;;
esac 
}
menu 
