#!/system/bin/bash
clear
menu(){
center "Welcome To Sos"
logo "Main-Menu"
center "Heheboi"
echo 
cout "[ Main Menu Of (sos) ]"
sleep 0.1
cout "[1] Extreme Mode."
sleep 0.1
cout "[2] Game-Center."
sleep 0.1
cout "[3] Img2Folder/Folder2Img."
sleep 0.1
cout "[4] Miscellaneous functions."
sleep 0.1
cout "[5] Performance Tweaks."
sleep 0.1
cout "[6] System Tweaks."
sleep 0.1
cout "[7] Update Kernel."
sleep 0.1
cout "[8] Update Mesa."
sleep 0.1
cout "[9] Auto-Timer PowerOff."
sleep 0.1
cout "[e] Exit from sos."
sleep 0.1
echo -e "[a]About_MOD."  
echo -e "\e[93;1m"
read -p "Enter your Option :- " c 
echo -e "\e[0m"
clear 
case $c in 
1)
bash /system/script/extreme
;;
2)
clear
game(){
center "Welcome"
logo "Game-Center"
center "Heheboi"
echo 
cout "1] Ghost Recoder(video only)."
cout "2] Return To Main Menu." 
cout "3] Exit." 
echo -e "\e[93;1m"
read -p "Enter The Option:- " c 
echo -e "\e[0m"
clear 
case $c in 
1)
bash /system/script/game/recoder 
;;
2)
bash /system/script/menu ;; 
3)
exit 
;;
*)
cout "AH Boi Here We Go Again."
sleep 0.7
clear 
game
;;
esac 
}
game
;;
3)
bash /system/script/img 
;;
4)
misc(){
center "Welcome"
logo "Miscellaneous"
center "Heheboi"
echo 
cout "1]Partition Mounter."
cout "2]Data Re-size." 
cout "3]System Re-size." 
cout "4]Google Service."
cout "5]Tablet Mode Or Desktop Mode." 
cout "6]Return To Main menu."
cout "7]Exit."
echo -e "\e[93;1m"
read -p "Enter The Option:- " c 
echo -e "\e[0m"
clear
case $c in 
1)
bash /system/script/misc/part 
;;
2)
bash /system/script/misc/data ;;
3)
bash /system/script/misc/system ;;
4)
bash /system/script/misc/google ;;
5)
bash /system/script/misc/cz ;; 
6)
bash /system/script/menu 
;;
7)
exit 
;;
*)
cout "Ah Boi Here We Go Again."
sleep 0.7
clear 
misc
;;
esac 
}
misc
;;
5)
bash /system/script/Performance ;;
6)
system_tweaks(){
center "Welcome"
logo "System-Tweaks"
center "Heheboi"
echo 
cout "1]Animations." 
cout "2]Cache."
cout "3]Firmware." 
cout "4]Init-Fix."
cout "5]Resolution."
cout "6]Return Main Menu."
cout "[e]Exit."
echo 
echo -e "\e[93;1m"
read -p "Enter The Option Here:- " c 
echo -e "\e[0m"   
clear 
case $c in 
1)
bash /system/script/systemtweaks/ani 
;;
2)
bash /system/script/systemtweaks/cache 
;;
3)
bash /system/script/systemtweaks/firmware
;;
4)
bash /system/script/systemtweaks/init 
;;
5)
bash /system/script/systemtweaks/resolution
;;
6)
clear 
bash /system/script/menu
;;
e)
exit 
;;
*)
cout "Ah Boi Here We go Again....!"
sleep 0.7
clear 
system_tweaks
;;
esac
}
system_tweaks
;;
7)
bash /system/script/kernel 
;;
8)
bash /system/script/mesa 
;;
9)
bash /system/script/poweroff
;;
e)
exit 
;;
a)
bash /system/script/about
;;
s)
bash /system/script/status
;;
b) 
if [ -f /system/etc/sounds/sos.bak ]; then 
st=$(echo on )
else
st=$(echo off)
fi
if [ -f /system/etc/sounds/sos.sos ]; then 
mv /system/etc/sounds/sos.sos /system/etc/sounds/sos.bak > /dev/null 2>&1
mv /system/etc/sounds/done.sos /system/etc/sounds/done.bak > /dev/null 2>&1
cout "Sound Off..!"
sleep 1
menu 
else 
mv /system/etc/sounds/sos.bak /system/etc/sounds/sos.sos > /dev/null 2>&1  
mv /system/etc/sounds/done.bak /system/etc/sounds/done.sos > /dev/null 2>&1
cout "Sound On..!"
sleep 1
menu 
fi
;;
*)
cout "Ah Boi Here We Go Again..!"
sleep 1
clear 
menu 
;;
esac 
}
menu 
