#!/system/bin/bash
C1="\e[31;1m"
C2="\e[32;1m"
C3="\e[33;1m"
C4="\e[34;1m"
C5="\e[35;1m"
C6="\e[36;1m"
CD="\e[0m"
enable()
{
cout "${C6}[ ENABLING PERFORMANCE GOVERNOR ]${CD}${CN}"
cd /system/etc/security/cacerts/.intel/init
rsync -aq init1 /system/etc/
cd /system/etc
mv -f init1 init.sh
cd /system/etc
chmod 755 init.sh
sleep 2
cout "${C6}[ TWEAKING I/O SCHEDULER ]${CD}${CN}"
cd /system/etc/security/cacerts/.intel/init
rsync -aq build1 /system/
cd /system
mv -f build1 build.prop
chmod 644 build.prop
sleep 2
cout "${C6}[ OPTIMIZING TCP CONGESTION CONTROLS ]${CD}${CN}"
sleep 2
cout "${C2}[ HeHe ]${CD}${CN}"
alsa_aplay /system/etc/sounds/done.sos > /dev/null 2>&1
sec=5
while [ $sec -ge 0 ]; do
echo -ne "\e[33;1mRebooting in:-\e[91;1m $sec \e[0m\033[0K\r"
let "sec=sec-1"
sleep 1
done
reboot    
}
disable()
{
cout "${C6}[ DISABLING PERFORMANCE GOVERNOR ]${CD}${CN}"
cd /system/etc/security/cacerts/.intel/init
rsync -aq init0 /system/etc/
cd /system/etc
mv -f init0 init.sh
cd /system/etc
chmod 755 init.sh
sleep 2
cout "${C6}[ SETTING UP ORIGINAL STATE OF I/O SCHEDULER ]${CD}${CN}"
cd /system/etc/security/cacerts/.intel/init
rsync -aq build0 /system/
cd /system
mv -f build0 build.prop
chmod 644 build.prop
sleep 2
cout "${C6}[ SETTING UP ORIGINAL STATE OF TCP CONGESTION CONTROLS ]${CD}${CN}"
sleep 2
cout "${C2}[ HeHe Boi ]${CD}${CN}"
alsa_aplay /system/etc/sounds/done.sos > /dev/null 2>&1
sec=5
while [ $sec -ge 0 ]; do
echo -ne "\e[33;1mRebooting in:-\e[91;1m $sec \e[0m\033[0K\r"
let "sec=sec-1"
sleep 1
done
reboot    
}
cli(){
center "Welcome"
logo "Performance"
center "Heheboi"
echo 
cout "${C4}[ THIS SCRIPT IS MADE BY SPECTRE ]${CD}${CN}"
cout "${C2}[ CPU GOVERNOR TWEAK ADDED BY xxDaKsHxx ]${CD}${CN}"
cout "${C3}[ THIS SCRIPT IS USED TO OPTIMIZE OVERALL PERFORMANCE OF THE SYSTEM  ]${CD}${CN}"
cout "${C2}[ Select the options below ]${CD}${CN}"
cout "${C3} [1] ENABLE  ${CD}${CN}"
cout "${C4} [2] DISABLE ${CD}${CN}"
cout "${C5} [3] Return To Main-Menu.${CD}${CN}"
cout "${C1} [4] Exit.${CD}${CN}"
echo -e "\e[93;1m"
read -p "Enter The Option:- " c 
echo -e "\e[0m"
clear
case $c in
1)
enable
;;
2)
disable
;;
3)
bash /system/script/menu
;;
4)
exit
;;
*)
clear
cout "${C3}Ah Boi Here We Go Again....${CD}${CN}"
sleep 1
cli
;;
esac
}
clear
cli
