#!/system/bin/bash
C1="\e[31;1m"
C2="\e[32;1m"
C3="\e[33;1m"
C4="\e[34;1m"
C5="\e[35;1m"
C6="\e[36;1m"
CD="\e[0m"
enable()
{
cout "[ ENABLING PERFORMANCE GOVERNOR ]"
cd /system/etc/security/cacerts/.intel/init
rsync -aq init1 /system/etc/
cd /system/etc
mv -f init1 init.sh
cd /system/etc
chmod 755 init.sh
sleep 2
cout "[ TWEAKING I/O SCHEDULER ]"
cd /system/etc/security/cacerts/.intel/init
rsync -aq build1 /system/
cd /system
mv -f build1 build.prop
chmod 644 build.prop
sleep 2
cout "[ OPTIMIZING TCP CONGESTION CONTROLS ]"
sleep 2
cout "HeHeBoi..!" &
alsa_aplay /system/etc/sounds/done.sos > /dev/null 2>&1
sec=5
while [ $sec -ge 0 ]; do
echo -ne "\e[33;1mRebooting in:-\e[91;1m $sec \e[0m\033[0K\r"
let "sec=sec-1"
sleep 1
done
reboot    
}
disable()
{
cout "[ DISABLING PERFORMANCE GOVERNOR ]"
cd /system/etc/security/cacerts/.intel/init
rsync -aq init0 /system/etc/
cd /system/etc
mv -f init0 init.sh
cd /system/etc
chmod 755 init.sh
sleep 2
cout "[ SETTING UP ORIGINAL STATE OF I/O SCHEDULER ]"
cd /system/etc/security/cacerts/.intel/init
rsync -aq build0 /system/
cd /system
mv -f build0 build.prop
chmod 644 build.prop
sleep 2
cout "[ SETTING UP ORIGINAL STATE OF TCP CONGESTION CONTROLS ]"
sleep 2
cout "[ HeHe Boi ]" &
alsa_aplay /system/etc/sounds/done.sos > /dev/null 2>&1
sec=5
while [ $sec -ge 0 ]; do
echo -ne "\e[33;1mRebooting in:-\e[91;1m $sec \e[0m\033[0K\r"
let "sec=sec-1"
sleep 1
done
reboot    
}
cli(){
center "Welcome"
logo "Performance"
center "Heheboi"
echo 
cout "[ THIS SCRIPT IS MADE BY SPECTRE ]"
cout "[ CPU GOVERNOR TWEAK ADDED BY xxDaKsHxx ]"
cout "[ THIS SCRIPT IS USED TO OPTIMIZE OVERALL PERFORMANCE OF THE SYSTEM  ]"
cout "[ Select the options below ]"
cout "[1] ENABLE."
cout "[2] DISABLE."
cout "[3] Return To Main-Menu."
cout "[4] Exit."
echo -e "\e[93;1m"
read -p "Enter The Option:- " c 
echo -e "\e[0m"
clear
case $c in
1)
enable
;;
2)
disable
;;
3)
bash /system/script/menu
;;
4)
exit
;;
*)
clear
cout "Ah Boi Here We Go Again....!"
sleep 1
cli
;;
esac
}
clear
cli
